// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_vertex_shader
#define  TXT_HEADER_vertex_shader


const char vertex_shader [] =
"#version 300 es\n"
"layout (location = 0) in vec3 pos_in;\n"
"//layout (location = 1) in float arg;\n"
"uniform mat4 model;\n"
"uniform mat4 view;\n"
"uniform mat4 projection;\n"
"uniform float v[10];\n"
"out vec3 vColor;\n"
"//in int gl_InstanceID;\n"
"void main() {\n"
"	vec3 pos = pos_in;\n"
"	vec3 offset;\n"
"	if (gl_InstanceID == 1) {  // 4 red\n"
"		offset = vec3(-2,1,-1);\n"
"		vColor = vec3(1,0,0);\n"
"		pos = vec3(0, pos_in.y, pos_in.x); // поворот в плоскость yz\n"
"	} else if (gl_InstanceID == 2) { // 3 green\n"
"		offset = vec3(0,1,-1);\n"
"		vColor = vec3(0,1,0);\n"
"		pos = vec3(0, pos_in.y, pos_in.x); // поворот в плоскость yz\n"
"	} else if (gl_InstanceID == 3) { // 2 yellow\n"
"		offset = vec3(-1,2,-1);\n"
"		vColor = vec3(1,1,0);\n"
"		pos = vec3(pos_in.x, 0, pos_in.y); // поворот в плоскость xz\n"
"	} else if (gl_InstanceID == 4) { // 1 blue\n"
"		offset = vec3(-1,0,-1);\n"
"		vColor = vec3(0,0,1);\n"
"		pos = vec3(pos_in.x, 0, pos_in.y); // поворот в плоскость xz\n"
"	} else {\n"
"		offset = vec3(-1,1,-2);\n"
"		vColor = vec3(1,0,1);\n"
"	}\n"
"	//  int a = floatBitsToInt(arg);\n"
"	//  if (a == 33) {\n"
"	//    vColor = vec3(0,1,0);\n"
"	//    gl_Position = projection * view * model * vec4(pos + offset, 1.0);\n"
"	//  } else if (a == 11) {\n"
"	//    vColor = vec3(1,0,0);\n"
"	//    vec3 newpos = vec3(pos.x, pos.y, pos.z);\n"
"	//    gl_Position = projection * view * model * vec4(newpos + offset, 1.0);\n"
"	//    //pos = ;\n"
"	//  }\n"
"	gl_Position = projection * view * model * vec4(pos + offset, 1.0);\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_vertex_shader
